# Generated by Django 5.0.3 on 2026-02-27 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_student_address_alter_student_detail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationlog',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
